apiVersion: stack.zncdata.net/v1alpha1
kind: TrinoCluster
metadata:
  labels:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino-sample
    app.kubernetes.io/part-of: trino-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trino-operator
  name: trino-sample
spec:
  image:
    repository: trinodb/trino
    tag: "423"
    pullPolicy: IfNotPresent
  service:
    port: 18080
    type: ClusterIP
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: traefik
      nginx.ingress.kubernetes.io/rewrite-target: /
    host: trino.example.com
  clusterConfig:
    nodeProperties:
      environment: "production"
      dataDir: /data/trino
      pluginDir: /usr/lib/trino/plugin
    configProperties:
      queryMaxMemory: "4GB"
      path: /etc/trino
      https:
        enabled: false
    exchangeManager:
      name: "filesystem"
    clusterMode: true
  coordinator:
    roleConfig:
      jvmProperties:
        maxHeapSize: "4G"
        gcMethodType: "UseG1GC"
        gcHeapRegionSize: "32M"
      configProperties:
        memoryHeapHeadroomPerNode: ""
        queryMaxMemoryPerNode: "1GB"
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
          matchLabels:
            app: default-coordinator
      foo:
        replicas: 1
        config:
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
          matchLabels:
            app: foo-coordinator
  worker:
    roleConfig:
      jvmProperties:
          maxHeapSize: "8G"
          gcMethodType: "UseG1GC"
          gcHeapRegionSize: "32M"
      configProperties:
          memoryHeapHeadroomPerNode: ""
          queryMaxMemoryPerNode: "1GB"
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
          matchLabels:
            app: default-worker
      foo:
        replicas: 1
        config:
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
          matchLabels:
            app: foo-worker
  securityContext:
    runAsUser: 1000
    fsGroup: 1000